name: sample_app
description: "Sample App for showcase"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
