name: sample_app
description: "Sample App for showcase"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  
  dio: 5.8.0+1
  equatable: 2.0.7
  flutter_bloc: 9.1.1
  get_it: 8.0.3
  json_annotation: 4.9.0
  json_serializable: 6.9.5
  logging: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15

flutter:
  uses-material-design: true
